### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Nico6101** [Nico6101/Expense-manager#1]
FATAL EXCEPTION: main
Process: com.rcpl.tabapp, PID: 4939
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is 
                                                  initialized correctly before accessing data from it.
                        at android.database.CursorWindow.nativeGetString(Native Method)
                        at android.database.CursorWindow.getString(CursorWindow.java:438)
                       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:61)
   at com.rcpl.tabapp.DatabaseView1Activity$MyCursorAdapter.bindView(DatabaseView1Activity.java:93)
                         at android.widget.CursorAdapter.getView(CursorAdapter.java:254)
                     at android.widget.AbsListView.obtainView(AbsListView.java:2459)
                        at android.widget.ListView.makeAndAddView(ListView.java:1889)
                                                                   at android.widget.ListView.fillDown(ListView.java:705)
                                                                   at android.widget.ListView.fillFromTop(ListView.java:766)
                                                                   at android.widget.ListView.layoutChildren(ListView.java:1690)
                                                                   at android.widget.AbsListView.onLayout(AbsListView.java:2222)
                                                                   at android.view.View.layout(View.java:15901)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5103)
                        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:598)
                                                                   at android.view.View.layout(View.java:15901)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5103)
                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
                                                                   at android.view.View.layout(View.java:15901)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5103)
      at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                   at android.view.View.layout(View.java:15901)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5103)
                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
                                                                   at android.view.View.layout(View.java:15901)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5103)
                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1954)
                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1808)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1717)
                                                                   at android.view.View.layout(View.java:15901)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5103)
                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
                                                                   at android.view.View.layout(View.java:15901)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5103)
                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2420)
                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2126)
                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6438)
                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)
                                       at android.view.Choreographer.doCallbacks(Choreographer.java:598)
                                         at android.view.Choreographer.doFrame(Choreographer.java:567)
                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:781)
                                                                   at android.os.Handler.handleCallback(Handler.java:810)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                   at android.os.Looper.loop(Looper.java:189)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5532)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)

**Comment by Nico6101** [comment]
i don't know how to resolve this..If anyone knows the solution.. kindly explain.. if you need more information about the problem .. it will be provided.
